name: "Lint (auth)"

on:
    # Run on every push to a branch other than main that changes auth/
    push:
        branches-ignore: [main]
        paths:
            - "auth/**"
            - ".github/workflows/auth-lint.yml"

env:
    FLUTTER_VERSION: "3.22.2"

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: auth
        steps:
            - name: Checkout code and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Flutter ${{ env.FLUTTER_VERSION  }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION  }}
                  cache: true

            - run: flutter pub get

            - run: flutter analyze --no-fatal-infos

            - name: Verify custom icon JSON
              run: cat assets/custom-icons/_data/custom-icons.json | jq empty
